name: "Transcode Killer"
guid: "a0444c3b-fe1c-4258-9e0f-a139fc093949"
version: 4
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Kills transcodes to prevent server overload."
description: "Kills transcodes above set resolutions to prevent server overload."
category: "Administration"
artifacts:
  - "Jellyfin.Plugin.TranscodeKiller.dll"
changelog: |-
  - Jellyfin 10.11 support (#7) @crobibero
  - Improve plugin description (#9) @dhlavaty
