name: "Transcode Killer"
guid: "a0444c3b-fe1c-4258-9e0f-a139fc093949"
version: "3"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Kills transcoded streams."
description: >
  Kills transcoded streams.

category: "General"
artifacts:
  - "Jellyfin.Plugin.TranscodeKiller.dll"
changelog: |-
